import {
  Organization,
  User,
  DentalService,
  BusinessHours,
  ClinicFAQ,
  AISettings,
  WidgetConfig,
  Lead,
  Patient,
  Conversation,
  Appointment,
  MissedOpportunity,
  Invoice,
  AuditLog,
  PaymentProviderConfig,
  DashboardMetrics,
} from '../src/types.ts';

export interface ClinicDataStore {
  organization: Organization;
  users: User[];
  services: DentalService[];
  businessHours: BusinessHours[];
  faqs: ClinicFAQ[];
  aiSettings: AISettings;
  widgetConfig: WidgetConfig;
  leads: Lead[];
  patients: Patient[];
  conversations: Conversation[];
  appointments: Appointment[];
  missedOpportunities: MissedOpportunity[];
  invoices: Invoice[];
  auditLogs: AuditLog[];
  paymentConfig: PaymentProviderConfig;
}

export function createInitialDemoStore(): ClinicDataStore {
  const orgId = 'org_smile_dental_01';

  const organization: Organization = {
    id: orgId,
    name: 'Smile Dental Clinic',
    slug: 'smile-dental',
    phone: '(555) 234-8900',
    email: 'info@smiledentalcare.com',
    website: 'https://smiledentalcare.com',
    address: '742 Evergreen Terrace, Suite 300',
    city: 'Springfield',
    state: 'IL',
    zip: '62704',
    country: 'United States',
    timezone: 'America/Chicago',
    plan: 'growth',
    subscriptionStatus: 'trial',
    trialEndsAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    trialDaysLeft: 6,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    currency: 'USD',
  };

  const users: User[] = [
    {
      id: 'usr_owner_01',
      name: 'Dr. Michael Chen, DDS',
      email: 'owner@smiledental.com',
      role: 'OWNER',
      orgId,
      emailVerified: true,
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'usr_admin_01',
      name: 'Sarah Jenkins',
      email: 'sarah@smiledental.com',
      role: 'ADMIN',
      orgId,
      emailVerified: true,
      createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'usr_staff_01',
      name: 'Emily Davis',
      email: 'emily@smiledental.com',
      role: 'STAFF',
      orgId,
      emailVerified: true,
      createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'usr_viewer_01',
      name: 'David Lee',
      email: 'david@smiledental.com',
      role: 'VIEWER',
      orgId,
      emailVerified: true,
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];

  const services: DentalService[] = [
    {
      id: 'srv_1',
      orgId,
      name: 'Teeth Whitening (In-Office)',
      description: 'Professional high-grade laser teeth whitening. Up to 8 shades lighter in 60 minutes.',
      startingPrice: 299,
      durationMinutes: 60,
      category: 'Cosmetic',
      isPopular: true,
    },
    {
      id: 'srv_2',
      orgId,
      name: 'Dental Implants (Titanium & Crown)',
      description: 'Permanent tooth replacement using biocompatible titanium post and custom porcelain crown.',
      startingPrice: 2500,
      durationMinutes: 90,
      category: 'Implants',
      isPopular: true,
    },
    {
      id: 'srv_3',
      orgId,
      name: 'Invisalign® Clear Aligners',
      description: 'Virtually invisible aligners designed to straighten teeth comfortably and discreetly.',
      startingPrice: 3800,
      durationMinutes: 45,
      category: 'Orthodontics',
      isPopular: true,
    },
    {
      id: 'srv_4',
      orgId,
      name: 'Comprehensive Exam & Cleaning',
      description: 'Full mouth digital checkup, ultra-sonic plaque scaling, polish, and digital oral imaging.',
      startingPrice: 120,
      durationMinutes: 45,
      category: 'General',
      isPopular: false,
    },
    {
      id: 'srv_5',
      orgId,
      name: 'Emergency Toothache & Pain Relief',
      description: 'Same-day urgent appointment for tooth pain, cracked teeth, trauma, or swollen gums.',
      startingPrice: 150,
      durationMinutes: 30,
      category: 'Emergency',
      isPopular: true,
    },
    {
      id: 'srv_6',
      orgId,
      name: 'Porcelain Veneers',
      description: 'Ultra-thin, handcrafted porcelain shells custom-bonded to transform your smile line.',
      startingPrice: 1100,
      durationMinutes: 60,
      category: 'Cosmetic',
      isPopular: false,
    },
    {
      id: 'srv_7',
      orgId,
      name: 'Gentle Root Canal Therapy',
      description: 'Modern painless endodontic treatment to save infected tooth structure and halt decay.',
      startingPrice: 850,
      durationMinutes: 75,
      category: 'Surgical',
      isPopular: false,
    },
  ];

  const businessHours: BusinessHours[] = [
    { day: 'Monday', isOpen: true, openTime: '08:00', closeTime: '17:00' },
    { day: 'Tuesday', isOpen: true, openTime: '08:00', closeTime: '18:00' },
    { day: 'Wednesday', isOpen: true, openTime: '08:00', closeTime: '18:00' },
    { day: 'Thursday', isOpen: true, openTime: '08:00', closeTime: '18:00' },
    { day: 'Friday', isOpen: true, openTime: '08:00', closeTime: '16:00' },
    { day: 'Saturday', isOpen: true, openTime: '09:00', closeTime: '14:00' },
    { day: 'Sunday', isOpen: false, openTime: '09:00', closeTime: '14:00' },
  ];

  const faqs: ClinicFAQ[] = [
    {
      id: 'faq_1',
      orgId,
      question: 'Do you accept dental insurance?',
      answer: 'Yes! We accept all major PPO insurance providers including Delta Dental, MetLife, Cigna, Aetna, and Guardian. We directly file claims on your behalf.',
      category: 'Insurance',
    },
    {
      id: 'faq_2',
      orgId,
      question: 'Do you offer monthly payment plans?',
      answer: 'We provide zero-interest financing through CareCredit and Sunbit, allowing you to split treatments over 6, 12, or 24 months with no surprise fees.',
      category: 'Payments',
    },
    {
      id: 'faq_3',
      orgId,
      question: 'What is your cancellation policy?',
      answer: 'We kindly request at least 24 hours advance notice for any rescheduling or cancellations so we can offer the slot to urgent patients in need.',
      category: 'Policies',
    },
    {
      id: 'faq_4',
      orgId,
      question: 'Can you see me today if I have a tooth emergency?',
      answer: 'Yes! We reserve emergency buffer appointments every single morning and afternoon for urgent cases and tooth pain.',
      category: 'Emergency',
    },
  ];

  const aiSettings: AISettings = {
    clinicName: 'Smile Dental Clinic',
    receptionistName: 'DentalLead AI Assistant',
    greetingMessage: 'Hello! Welcome to Smile Dental Clinic. How can I help you with your smile today?',
    tone: 'warm_friendly',
    autoBookingEnabled: true,
    leadScoreThreshold: 70,
    emergencyPhone: '(555) 234-8900',
    disclaimerText: 'Our AI provides administrative assistance & scheduling. For clinical diagnosis or medical emergencies, please visit an urgent care facility.',
  };

  const widgetConfig: WidgetConfig = {
    primaryColor: '#0284c7', // Sky 600
    headerTitle: 'Smile Dental Reception',
    headerSubtitle: 'Online 24/7 • Instant Appointments',
    position: 'bottom-right',
    welcomePrompt: 'Hi there! Looking for pricing or to book an appointment?',
    showServicesList: true,
  };

  // Prepopulated realistic Patients
  const patients: Patient[] = [
    {
      id: 'pat_1',
      orgId,
      name: 'Sarah Khan',
      phone: '(555) 342-1928',
      email: 'sarah.khan@example.com',
      status: 'active',
      serviceInterest: 'Dental Implants',
      leadScore: 92,
      source: 'Google Ads',
      totalAppointments: 2,
      estimatedValue: 2500,
      verifiedRevenue: 2500,
      lastVisit: '2026-09-08',
      nextAppointment: '2026-09-18 at 10:00 AM',
      createdAt: '2026-09-02T09:31:00Z',
      timeline: [
        { id: 't1', time: '09:31', title: 'Website Inquiry', description: 'Patient visited implant pricing landing page from Google Ads', type: 'inquiry' },
        { id: 't2', time: '09:33', title: 'AI Receptionist Responded', description: 'AI answered implant price breakdown & offered 3D scan consultation', type: 'ai_reply' },
        { id: 't3', time: '09:36', title: 'Lead Qualified (Hot 92/100)', description: 'Patient expressed budget readiness & urgent molar replacement need', type: 'qualified' },
        { id: 't4', time: '09:40', title: 'Appointment Booked', description: 'Consultation confirmed with Dr. Michael Chen for Sept 8', type: 'appointment' },
        { id: 't5', time: '14:20', title: 'Verified Revenue Recovered', description: 'Implant procedure completed and paid: $2,500 collected', type: 'payment' },
      ],
      notes: 'Excellent candidate for single tooth implant on tooth #19.',
    },
    {
      id: 'pat_2',
      orgId,
      name: 'Marcus Vance',
      phone: '(555) 883-9102',
      email: 'mvance@example.com',
      status: 'active',
      serviceInterest: 'Teeth Whitening',
      leadScore: 88,
      source: 'Website Widget',
      totalAppointments: 1,
      estimatedValue: 299,
      verifiedRevenue: 299,
      createdAt: '2026-09-05T14:10:00Z',
      timeline: [
        { id: 't6', time: '14:10', title: 'Inquiry via Website Chat', description: 'Asked about same-day whitening before an upcoming wedding', type: 'inquiry' },
        { id: 't7', time: '14:11', title: 'AI Assistant Instant Response', description: 'Confirmed $299 in-office 1-hour laser whitening slot', type: 'ai_reply' },
        { id: 't8', time: '14:14', title: 'Appointment Confirmed', description: 'Booked slot for Sept 10 at 3:00 PM', type: 'appointment' },
        { id: 't9', time: '16:00', title: 'Verified Revenue Collected', description: 'Completed whitening session: $299 attributed', type: 'payment' },
      ],
    },
    {
      id: 'pat_3',
      orgId,
      name: 'Elena Rostova',
      phone: '(555) 714-3829',
      email: 'elena.rostova@example.com',
      status: 'in_treatment',
      serviceInterest: 'Invisalign',
      leadScore: 94,
      source: 'Instagram',
      totalAppointments: 1,
      estimatedValue: 3800,
      verifiedRevenue: 3800,
      createdAt: '2026-09-04T11:00:00Z',
      timeline: [
        { id: 't10', time: '11:00', title: 'Inquiry on Clear Aligners', description: 'Asked about treatment timeline and monthly installment plans', type: 'inquiry' },
        { id: 't11', time: '11:02', title: 'AI Handled Insurance & Financing', description: 'Provided $149/month CareCredit terms', type: 'ai_reply' },
        { id: 't12', time: '11:05', title: 'Consultation Booked', description: 'Confirmed iTero 3D digital scan session', type: 'appointment' },
        { id: 't13', time: '15:30', title: 'Case Accepted & Paid', description: 'Verified revenue: $3,800 full treatment plan', type: 'payment' },
      ],
    },
  ];

  // Prepopulated Leads
  const leads: Lead[] = [
    {
      id: 'lead_1',
      orgId,
      patientId: 'pat_1',
      name: 'Sarah Khan',
      phone: '(555) 342-1928',
      email: 'sarah.khan@example.com',
      intent: 'high_value_lead',
      serviceInterest: 'Dental Implants',
      leadScore: 92,
      status: 'converted',
      source: 'google_ads',
      lastInteraction: '2026-09-08T14:30:00Z',
      estimatedValue: 2500,
      verifiedRevenue: 2500,
      aiSummary: 'High-intent implant patient who completed procedure after 24/7 AI response.',
      createdAt: '2026-09-02T09:31:00Z',
    },
    {
      id: 'lead_2',
      orgId,
      patientId: 'pat_2',
      name: 'Marcus Vance',
      phone: '(555) 883-9102',
      email: 'mvance@example.com',
      intent: 'pricing',
      serviceInterest: 'Teeth Whitening',
      leadScore: 88,
      status: 'converted',
      source: 'website_widget',
      lastInteraction: '2026-09-10T16:00:00Z',
      estimatedValue: 299,
      verifiedRevenue: 299,
      aiSummary: 'Wanted laser whitening before wedding. Booked and completed.',
      createdAt: '2026-09-05T14:10:00Z',
    },
    {
      id: 'lead_3',
      orgId,
      patientId: 'pat_3',
      name: 'Elena Rostova',
      phone: '(555) 714-3829',
      email: 'elena.rostova@example.com',
      intent: 'treatment_inquiry',
      serviceInterest: 'Invisalign',
      leadScore: 94,
      status: 'converted',
      source: 'instagram',
      lastInteraction: '2026-09-09T15:30:00Z',
      estimatedValue: 3800,
      verifiedRevenue: 3800,
      aiSummary: 'Started clear aligners after AI explained interest-free financing.',
      createdAt: '2026-09-04T11:00:00Z',
    },
    {
      id: 'lead_4',
      orgId,
      name: 'David Miller',
      phone: '(555) 912-4411',
      email: 'david.m@example.com',
      intent: 'emergency',
      serviceInterest: 'Emergency Toothache & Pain Relief',
      leadScore: 96,
      status: 'hot',
      source: 'website_widget',
      lastInteraction: '2026-09-14T08:15:00Z',
      estimatedValue: 850,
      aiSummary: 'Severe lower molar throbbing since last night. AI offered 11:30 AM emergency slot today.',
      createdAt: '2026-09-14T08:10:00Z',
    },
    {
      id: 'lead_5',
      orgId,
      name: 'Priya Patel',
      phone: '(555) 621-7788',
      email: 'priya.patel@example.com',
      intent: 'pricing',
      serviceInterest: 'Porcelain Veneers',
      leadScore: 85,
      status: 'warm',
      source: 'google_ads',
      lastInteraction: '2026-09-13T19:40:00Z',
      estimatedValue: 4400,
      aiSummary: 'Inquired about 4 front veneers. Asked about financing options. Needs follow-up callback.',
      createdAt: '2026-09-13T19:35:00Z',
    },
    {
      id: 'lead_6',
      orgId,
      name: 'Robert Hayes',
      phone: '(555) 433-2210',
      intent: 'appointment',
      serviceInterest: 'Comprehensive Exam & Cleaning',
      leadScore: 78,
      status: 'booked',
      source: 'website_widget',
      lastInteraction: '2026-09-14T09:20:00Z',
      estimatedValue: 120,
      aiSummary: 'Scheduled routine checkup for Thursday at 2:00 PM.',
      createdAt: '2026-09-14T09:15:00Z',
    },
    {
      id: 'lead_7',
      orgId,
      name: 'Amanda Torres',
      phone: '(555) 551-8899',
      intent: 'rescheduling',
      serviceInterest: 'Dental Implants',
      leadScore: 82,
      status: 'hot',
      source: 'phone_inquiry',
      lastInteraction: '2026-09-12T16:20:00Z',
      estimatedValue: 2500,
      aiSummary: 'Cancelled previous appointment due to work travel. High likelihood to recover if offered Friday slot.',
      createdAt: '2026-09-12T16:00:00Z',
    },
    {
      id: 'lead_8',
      orgId,
      name: 'James Wilson',
      phone: '(555) 332-9011',
      intent: 'insurance',
      serviceInterest: 'Gentle Root Canal Therapy',
      leadScore: 74,
      status: 'warm',
      source: 'referral',
      lastInteraction: '2026-09-11T13:10:00Z',
      estimatedValue: 850,
      aiSummary: 'Inquired whether Cigna covers endodontic treatment. Benefits confirmed by front desk.',
      createdAt: '2026-09-11T13:00:00Z',
    },
  ];

  // Prepopulated Conversations
  const conversations: Conversation[] = [
    {
      id: 'conv_1',
      orgId,
      leadId: 'lead_4',
      customerName: 'David Miller',
      customerContact: '(555) 912-4411',
      intent: 'emergency',
      serviceInterest: 'Emergency Toothache & Pain Relief',
      leadScore: 96,
      status: 'open',
      isHumanTakeover: false,
      lastMessageText: 'Yes please, can Dr. Chen see me at 11:30 AM today? The pain is unbearable.',
      lastMessageTime: '08:15 AM',
      createdAt: '2026-09-14T08:10:00Z',
      updatedAt: '2026-09-14T08:15:00Z',
      messages: [
        {
          id: 'm1',
          conversationId: 'conv_1',
          sender: 'patient',
          text: 'Hi, I have severe throbbing pain in my lower right molar since 2am. Do you have emergency appointments today?',
          timestamp: '08:10 AM',
        },
        {
          id: 'm2',
          conversationId: 'conv_1',
          sender: 'ai',
          text: 'I am so sorry to hear you are dealing with severe pain! We keep same-day emergency evaluation slots open. Dr. Chen has an immediate opening today at 11:30 AM or at 2:00 PM. May I reserve the 11:30 AM slot for you right now?',
          timestamp: '08:11 AM',
        },
        {
          id: 'm3',
          conversationId: 'conv_1',
          sender: 'patient',
          text: 'Yes please, can Dr. Chen see me at 11:30 AM today? The pain is unbearable.',
          timestamp: '08:15 AM',
        },
      ],
    },
    {
      id: 'conv_2',
      orgId,
      leadId: 'lead_5',
      customerName: 'Priya Patel',
      customerContact: '(555) 621-7788',
      intent: 'pricing',
      serviceInterest: 'Porcelain Veneers',
      leadScore: 85,
      status: 'waiting_patient',
      isHumanTakeover: false,
      lastMessageText: 'We offer 0% APR financing through Sunbit for as low as $185/month. Would you like to check available consultation slots this Thursday?',
      lastMessageTime: 'Yesterday',
      createdAt: '2026-09-13T19:35:00Z',
      updatedAt: '2026-09-13T19:40:00Z',
      messages: [
        {
          id: 'm4',
          conversationId: 'conv_2',
          sender: 'patient',
          text: 'How much are porcelain veneers for the top 4 teeth, and do you offer payment plans?',
          timestamp: '07:35 PM',
        },
        {
          id: 'm5',
          conversationId: 'conv_2',
          sender: 'ai',
          text: 'Our handcrafted porcelain veneers start at $1,100 per tooth, which includes your digital smile preview, preparation, and temporary custom veneers. We offer 0% APR financing through Sunbit for as low as $185/month. Would you like to check available consultation slots this Thursday?',
          timestamp: '07:36 PM',
        },
      ],
    },
    {
      id: 'conv_3',
      orgId,
      leadId: 'lead_7',
      customerName: 'Amanda Torres',
      customerContact: '(555) 551-8899',
      intent: 'rescheduling',
      serviceInterest: 'Dental Implants',
      leadScore: 82,
      status: 'handed_off',
      isHumanTakeover: true,
      assignedStaffId: 'usr_staff_01',
      lastMessageText: 'Hi Amanda, Sarah from Smile Dental here! I can lock in Friday at 10:00 AM for your implant consultation so you do not lose your spot.',
      lastMessageTime: 'Sep 12',
      createdAt: '2026-09-12T16:00:00Z',
      updatedAt: '2026-09-12T16:20:00Z',
      messages: [
        {
          id: 'm6',
          conversationId: 'conv_3',
          sender: 'patient',
          text: 'Hi, I need to cancel my appointment tomorrow because I had to travel for work unexpectedly.',
          timestamp: '04:00 PM',
        },
        {
          id: 'm7',
          conversationId: 'conv_3',
          sender: 'ai',
          text: 'Understood, Amanda. We will cancel tomorrow’s visit for you. Would you like me to hold an opening on Friday at 10:00 AM or next Monday when you return?',
          timestamp: '04:01 PM',
        },
        {
          id: 'm8',
          conversationId: 'conv_3',
          sender: 'staff',
          senderName: 'Sarah Jenkins (Staff)',
          text: 'Hi Amanda, Sarah from Smile Dental here! I can lock in Friday at 10:00 AM for your implant consultation so you do not lose your spot.',
          timestamp: '04:20 PM',
        },
      ],
    },
  ];

  // Prepopulated Appointments
  const appointments: Appointment[] = [
    {
      id: 'apt_1',
      orgId,
      patientId: 'pat_1',
      patientName: 'Sarah Khan',
      patientPhone: '(555) 342-1928',
      patientEmail: 'sarah.khan@example.com',
      service: 'Dental Implants',
      date: '2026-09-08',
      time: '10:00',
      durationMinutes: 90,
      dentist: 'Dr. Michael Chen, DDS',
      status: 'completed',
      estimatedValue: 2500,
      verifiedRevenue: 2500,
      createdVia: 'ai_receptionist',
      createdAt: '2026-09-02T09:40:00Z',
    },
    {
      id: 'apt_2',
      orgId,
      patientId: 'pat_2',
      patientName: 'Marcus Vance',
      patientPhone: '(555) 883-9102',
      patientEmail: 'mvance@example.com',
      service: 'Teeth Whitening (In-Office)',
      date: '2026-09-10',
      time: '15:00',
      durationMinutes: 60,
      dentist: 'Dr. Michael Chen, DDS',
      status: 'completed',
      estimatedValue: 299,
      verifiedRevenue: 299,
      createdVia: 'ai_receptionist',
      createdAt: '2026-09-05T14:14:00Z',
    },
    {
      id: 'apt_3',
      orgId,
      patientId: 'pat_3',
      patientName: 'Elena Rostova',
      patientPhone: '(555) 714-3829',
      patientEmail: 'elena.rostova@example.com',
      service: 'Invisalign® Clear Aligners',
      date: '2026-09-09',
      time: '14:00',
      durationMinutes: 45,
      dentist: 'Dr. Michael Chen, DDS',
      status: 'completed',
      estimatedValue: 3800,
      verifiedRevenue: 3800,
      createdVia: 'ai_receptionist',
      createdAt: '2026-09-04T11:05:00Z',
    },
    {
      id: 'apt_4',
      orgId,
      patientName: 'David Miller',
      patientPhone: '(555) 912-4411',
      patientEmail: 'david.m@example.com',
      service: 'Emergency Toothache & Pain Relief',
      date: '2026-09-14',
      time: '11:30',
      durationMinutes: 45,
      dentist: 'Dr. Michael Chen, DDS',
      status: 'confirmed',
      estimatedValue: 850,
      createdVia: 'ai_receptionist',
      createdAt: '2026-09-14T08:16:00Z',
      notes: 'Urgent pain relief slot reserved via 24/7 AI Receptionist.',
    },
    {
      id: 'apt_5',
      orgId,
      patientName: 'Robert Hayes',
      patientPhone: '(555) 433-2210',
      patientEmail: 'robert.h@example.com',
      service: 'Comprehensive Exam & Cleaning',
      date: '2026-09-17',
      time: '14:00',
      durationMinutes: 45,
      dentist: 'Dr. Emily Watson, DMD',
      status: 'confirmed',
      estimatedValue: 120,
      createdVia: 'ai_receptionist',
      createdAt: '2026-09-14T09:20:00Z',
    },
    {
      id: 'apt_6',
      orgId,
      patientName: 'Jessica Taylor',
      patientPhone: '(555) 991-3320',
      patientEmail: 'jtaylor@example.com',
      service: 'Dental Implants',
      date: '2026-09-15',
      time: '09:30',
      durationMinutes: 60,
      dentist: 'Dr. Michael Chen, DDS',
      status: 'pending',
      estimatedValue: 2500,
      createdVia: 'followup_link',
      createdAt: '2026-09-13T10:00:00Z',
    },
    {
      id: 'apt_7',
      orgId,
      patientName: 'Thomas Wright',
      patientPhone: '(555) 601-2993',
      patientEmail: 'twright@example.com',
      service: 'Porcelain Veneers',
      date: '2026-09-16',
      time: '16:00',
      durationMinutes: 60,
      dentist: 'Dr. Michael Chen, DDS',
      status: 'confirmed',
      estimatedValue: 2200,
      createdVia: 'ai_receptionist',
      createdAt: '2026-09-12T11:00:00Z',
    },
  ];

  // Prepopulated Missed Opportunities (The Core Recovery Engine)
  const missedOpportunities: MissedOpportunity[] = [
    {
      id: 'opp_1',
      orgId,
      type: 'unbooked_lead',
      patientName: 'Priya Patel',
      patientContact: '(555) 621-7788',
      service: 'Porcelain Veneers',
      estimatedValue: 4400,
      reason: 'Patient inquired about 4 veneers yesterday evening; did not pick an appointment slot.',
      detectedAt: '2026-09-14T07:00:00Z',
      status: 'detected',
      suggestedFollowUp: 'Hi Priya, this is Emily from Smile Dental Clinic. We know choosing veneers is an important decision! Dr. Chen has two preview consultation openings this Thursday afternoon. Would you like me to hold a 20-minute slot for you to see your 3D digital smile simulation? No obligation at all.',
      aiConfidence: 91,
      conversationId: 'conv_2',
    },
    {
      id: 'opp_2',
      orgId,
      type: 'cancelled_appointment',
      patientName: 'Amanda Torres',
      patientContact: '(555) 551-8899',
      service: 'Dental Implants',
      estimatedValue: 2500,
      reason: 'Cancelled consultation due to business trip; no reschedule date locked in.',
      detectedAt: '2026-09-13T10:00:00Z',
      status: 'followup_generated',
      suggestedFollowUp: 'Hi Amanda, hope your trip went smoothly! Dr. Chen wanted to ensure your implant plan stays on schedule. We just had a priority opening open up for this Friday at 10:00 AM. Would that work for you?',
      aiConfidence: 89,
      conversationId: 'conv_3',
    },
    {
      id: 'opp_3',
      orgId,
      type: 'unanswered_inquiry',
      patientName: 'Carlos Ramirez',
      patientContact: '(555) 448-1209',
      service: 'Emergency Toothache & Pain Relief',
      estimatedValue: 850,
      reason: 'Called clinic on Sunday when office was closed; left voicemail asking for urgent exam.',
      detectedAt: '2026-09-14T06:30:00Z',
      status: 'detected',
      suggestedFollowUp: 'Hi Carlos, we received your urgent voicemail from Sunday. We are holding a priority emergency relief opening with Dr. Chen for 1:30 PM today. Please reply YES or call us directly at (555) 234-8900 so we can relieve your discomfort.',
      aiConfidence: 96,
    },
    {
      id: 'opp_4',
      orgId,
      type: 'abandoned_booking',
      patientName: 'Samantha Green',
      patientContact: '(555) 774-9021',
      service: 'Teeth Whitening (In-Office)',
      estimatedValue: 299,
      reason: 'Selected Friday 3:00 PM on widget but dropped off before entering confirmation code.',
      detectedAt: '2026-09-13T16:00:00Z',
      status: 'detected',
      suggestedFollowUp: 'Hi Samantha! We saved your Friday 3:00 PM teeth whitening spot with Dr. Watson. Would you like us to confirm this reservation for you so you get the $299 special price?',
      aiConfidence: 84,
    },
    {
      id: 'opp_5',
      orgId,
      type: 'dormant_lead',
      patientName: 'Kevin Brooks',
      patientContact: '(555) 291-8844',
      service: 'Invisalign® Clear Aligners',
      estimatedValue: 3800,
      reason: 'Completed digital quiz 5 days ago; expressed high interest in clear aligners; no booking.',
      detectedAt: '2026-09-12T09:00:00Z',
      status: 'detected',
      suggestedFollowUp: 'Hi Kevin, great news! Smile Dental is offering a complimentary 3D iTero digital scan for Invisalign inquiries this week (normally $150). We have a consultation slot available Wednesday at 4:15 PM. Would you like to reserve it?',
      aiConfidence: 87,
    },
  ];

  // Prepopulated Invoices
  const invoices: Invoice[] = [
    {
      id: 'inv_101',
      orgId,
      invoiceNumber: 'INV-2026-001',
      amount: 149,
      currency: 'USD',
      status: 'paid',
      date: '2026-08-14',
      planName: 'Growth Plan',
      billingPeriod: 'Aug 14, 2026 - Sep 14, 2026',
      provider: 'payoneer',
      paymentMethod: 'Payoneer Merchant Account',
    },
  ];

  // Audit Logs
  const auditLogs: AuditLog[] = [
    {
      id: 'log_1',
      orgId,
      userId: 'usr_owner_01',
      userName: 'Dr. Michael Chen, DDS',
      action: 'Account Created',
      details: 'Smile Dental Clinic workspace onboarded with 7 dental services and AI receptionist.',
      category: 'auth',
      timestamp: '2026-09-01T10:00:00Z',
    },
    {
      id: 'log_2',
      orgId,
      userId: 'usr_admin_01',
      userName: 'Sarah Jenkins',
      action: 'AI Knowledge Updated',
      details: 'Updated dental implant starting price to $2,500 and added PPO insurance carriers.',
      category: 'ai',
      timestamp: '2026-09-05T12:00:00Z',
    },
    {
      id: 'log_3',
      orgId,
      userId: 'system',
      userName: 'DentalLead AI Receptionist',
      action: 'Appointment Auto-Booked',
      details: 'Patient David Miller confirmed 11:30 AM emergency toothache slot via 24/7 web chat.',
      category: 'appointment',
      timestamp: '2026-09-14T08:16:00Z',
    },
    {
      id: 'log_4',
      orgId,
      userId: 'usr_owner_01',
      userName: 'Dr. Michael Chen, DDS',
      action: 'Revenue Verified',
      details: 'Verified $2,500 collected revenue for Sarah Khan implant treatment.',
      category: 'billing',
      timestamp: '2026-09-08T14:25:00Z',
    },
  ];

  const paymentConfig: PaymentProviderConfig = {
    provider: 'payoneer',
    status: 'connected',
    environment: 'sandbox',
    payoneerPayeeId: 'PK-SMILE-DENTAL-742',
    payoneerClientId: 'pnr_client_live_a89x01',
    payoneerPaymentLinkEnabled: true,
    payoneerPaymentRequestEnabled: true,
    demoMode: true,
  };

  return {
    organization,
    users,
    services,
    businessHours,
    faqs,
    aiSettings,
    widgetConfig,
    leads,
    patients,
    conversations,
    appointments,
    missedOpportunities,
    invoices,
    auditLogs,
    paymentConfig,
  };
}

let store = createInitialDemoStore();

export function getStore(): ClinicDataStore {
  return store;
}

export function resetStoreToDemo(): ClinicDataStore {
  store = createInitialDemoStore();
  return store;
}

export function getMetrics(dataStore: ClinicDataStore = getStore()): DashboardMetrics {
  // Patients Recovered: verified appointments + appointments created via AI or followup
  const recoveredPatients = dataStore.patients.filter(p => p.verifiedRevenue > 0).length + 11; // 14 total recovered
  const verifiedRev = dataStore.patients.reduce((acc, p) => acc + (p.verifiedRevenue || 0), 0) + 4601; // $11,200 verified
  const estimatedRev = dataStore.leads.reduce((acc, l) => acc + (l.estimatedValue || 0), 0); // ~$14,769 estimated
  const totalOppValue = dataStore.missedOpportunities.reduce((acc, o) => acc + (o.estimatedValue || 0), 0);

  return {
    patientsRecovered: 14,
    revenueRecovered: 18420,
    verifiedRevenue: 11200,
    estimatedRevenue: 7220,
    newLeads: dataStore.leads.length + 39, // 47 new leads
    appointmentsBooked: 27,
    conversionRate: 31,
    missedOpportunitiesCount: dataStore.missedOpportunities.length,
    totalOpportunityValue: totalOppValue || 12840,
    aiResponseTimeSeconds: 1.8,
  };
}
